---
# this is the config that will be loaded as default by main.py
# Please follow the provided structure (this will ensuring all baseline follow
# a similar configuration structure and hence be easy to customise)

num_clients: 100
num_rounds: 10
batch_size: 32
local_epochs: 5
fraction_samples: 1.0
seed: 42
alpha: 2

client_resources:
  num_cpus: 1
  num_gpus: 0

dataset:
  dataset: "fmnist"

model:
  # model config

# variant of the strategy: "base", "cpow" for cpow, "rpow" for rpow
variant: "rpow"
b: 64

strategy:
  _target_: strategy.PowerOfChoice
  d: 15
  ck: 3

client:
  # client config
