---
# this is the config that will be loaded as default by main.py
# Please follow the provided structure (this will ensuring all baseline follow
# a similar configuration structure and hence be easy to customise)

num_clients: 100
num_rounds: 200
batch_size: 32
local_epochs: 5
fraction_samples: 1.0
seed: 42
alpha: 2
is_cnn: False

client_resources:
  num_cpus: 1
  num_gpus: 0

dataset:
  dataset: "fmnist"

model:
  # model config

# variant of the strategy: "rand" for FedAvg strategy ,"base", "cpow" for cpow, "rpow" for rpow
variant: "base"
b: 64

strategy:
  _target_: strategy.PowerOfChoice
  d: 6
  ck: 3

client:
  # client config

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${dataset.dataset}_${variant}_d${strategy.d}_CK${strategy.ck}