---
# this is the config that will be loaded as default by main.py
# Please follow the provided structure (this will ensuring all baseline follow
# a similar configuration structure and hence be easy to customise)

num_clients: 100 # number of clients
num_rounds: 5 # number of rounds
local_epochs_default: 2 # number of local epochs
batch_size_default: 32 # batch size
fraction_samples_default: 1.0 

# Which parameters to vary, NOTE: only one of these can be True
local_epochs_varying: False # whether to vary local epochs
batch_size_varying: False # whether to vary batch size
fraction_samples_varying: True # whether to vary fraction of samples

comp_time: 30 # computation time in seconds for each client

seed: 42

dataset:
  dataset: "mnist"
  num_classes: 10

model:
  # model config

strategy:
  _target_: # points to your strategy (either custom or exiting in Flower)
  # rest of strategy config

client:
  mean_ips: 100
  var_ips: 50